# -*- mode: restclient -*-

:url = http://localhost:3001

:headers = <<
content-type: application/json
#

GET :url/version
:headers
#

GET :url
:headers
#

POST :url/login
:headers
{
  "username": "test",
  "password1": "pass",
  "password2": "passx"
}
#

POST :url/comment
:headers
{
  "username": "test",
  "password": "pass",
  "message": "Good stuff"
}
#

GET :url/comments
:headers
#
